name 'olyn_percona'
maintainer 'Scott Richardson'
maintainer_email 'dev@grogwood.com'
chef_version '~> 16'
license 'GPL-3.0'
supports 'debian', '>= 10'
source_url 'https://gitlab.com/olyn/olyn_percona'
description 'Installs and configures Percona'
version '1.0.2'

provides 'olyn_percona::default'
provides 'olyn_percona::bootstrap'
provides 'olyn_percona::common'
provides 'olyn_percona::databases'
provides 'olyn_percona::percona'
provides 'olyn_percona::percona'
recipe 'olyn_percona::default', 'Installs and configures Percona cluster on the server'
recipe 'olyn_percona::common', 'Shared blocks for the Percona cookbook'
recipe 'olyn_percona::bootstrap', 'Bootstraps and initiates the Percona cluster'
recipe 'olyn_percona::databases', 'Creates and imports databases'
recipe 'olyn_percona::percona', 'Installs Percona and configures files'
recipe 'olyn_percona::users', 'Creates database users'
